# Use this set to assign a list of default pullSecrets
#  - name: docker-registry-secret
#  - name: internal-registry-secret
imagePullSecrets: []

imagePullPolicy: Always

php:
  image:
    repository: vuongxuongminh/docker-helm-laravel-php
    tag: prod
  supervisor:
    basicAuth:
      username: 'user'
      password: '!ChangeMe!'
    replicaCount: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    ## Additional deployment annotations
    podAnnotations: {}
    resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 256Mi
  fpm:
    replicaCount: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    ## Additional deployment annotations
    podAnnotations: {}
    resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 256Mi
  env: 'production'
  debug: 'false'
  secret: '!ChangeMe!'
  trustedProxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

nginx:
  image:
    repository: vuongxuongminh/docker-helm-laravel-nginx
    tag: prod
  replicaCount: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}
  resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: false
  nginx:
    hostName: 'nginx.example'
    # Tls secret name only affect when `tls` bellow is true.
    tlsSecret: 'nginx-tls'
  supervisor:
    hostName: 'supervisor.example'
    # Tls secret name only affect when `tls` bellow is true.
    tlsSecret: 'supervisor-tls'

mysql:
  internal: true
  # TODO: Move it to _helpers.tpl when issue: https://github.com/helm/helm/issues/3920 solved
  fullnameOverride: 'sub-chart-mysql'
  mysqlDatabase: test
  mysqlUser: user
  mysqlPassword: '!ChangeMe!'
#  mysqlRootPassword: 'root'
  # Persist data to a persistent volume
  persistence:
    enabled: false
  nodeSelector: {}
  tolerations: []
  ## Additional deployment annotations
  podAnnotations: {}
  resources: {}
  # See more config at https://github.com/helm/charts/tree/master/stable/mysql

  # Set when you want to use external MySQL. Affect only `mysql.internal` is false.
  externalHost: ''
  externalPort: 3306
  externalUser: ''
  externalPassword: ''
  externalDatabase: ''

rabbitmq:
  internal: true
  # TODO: Move it to _helpers.tpl when issue: https://github.com/helm/helm/issues/3920 solved
  fullnameOverride: 'sub-chart-rabbitmq'
  updateStrategy:
    type: 'OnDelete'
  persistence:
    enabled: false
  service:
    port: 5672
  rabbitmq:
    username: user
    password: '!ChangeMe!'
  ingress:
    enabled: true
    tls: false
    # Tls secret only affect when `tls` bellow is true.
    tlsSecret: 'rabbitmq-tls'
    hostName: 'rabbitmq.example'
    annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}
  resources: {}
  # See more config at https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq

  # Set when you want to use external RabbitMQ. Affect only `rabbitmq.internal` is false.
  externalHost: ''
  externalPort: 5672
  externalUser: ''
  externalPassword: ''