apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.existingServerBlockConfigmap }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  server.conf: |
    server {
      listen 0.0.0.0:8080;

      root /laravel/public;

      location / {
          # try to serve file directly, fallback to index.php
          try_files $uri /index.php$is_args$args;
      }

      location ~ ^/index\.php(/|$) {
          fastcgi_pass 0.0.0.0:9000;

          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;

          fastcgi_param DOCUMENT_ROOT $realpath_root;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

          internal;
      }

      location /status {
          stub_status on;
          access_log   off;
          allow 127.0.0.1;
          deny all;
      }
    }
