apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fpm" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.fpm.env | quote }}
  APP_DEBUG: {{ .Values.global.fpm.debug | quote }}
  APP_URL: {{ .Values.global.fpm.url | quote }}