apiVersion: v1
kind: Secret
metadata:
  name: {{ template "php" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.php.secret | b64enc | quote }}
  DB_HOST: {{ include "databaseHost" . | b64enc | quote }}
  DB_PORT: {{ include "databasePort" . | b64enc | quote }}
  DB_DATABASE: {{ include "databaseName" . | b64enc | quote }}
  DB_USERNAME: {{ include "databaseUser" . | b64enc | quote }}
  DB_PASSWORD: {{ include "databasePassword" . | b64enc | quote }}
  RABBITMQ_HOST: {{ include "rabbitMQHost" . | b64enc | quote }}
  RABBITMQ_PORT: {{ include "rabbitMQPort" . | b64enc | quote }}
  RABBITMQ_USER: {{ include "rabbitMQUser" . | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ include "rabbitMQPassword" . | b64enc | quote }}
